### ISSUE TITLE
An error was encountered when setting batch_size to 1 in sequence_to_sequence_implementation.ipynb（when batch_size > 1,it 's ok）

### ISSUE THREAD

**Issue by fanfanba** [udacity/deep-learning#206]
in my code, set:
embedding_dim = 200

error info:
Traceback (most recent call last):
  File "my_encoder_decoder.py", line 369, in <module>
    main(sys.argv[1])
  File "my_encoder_decoder.py", line 346, in main
    my_qa.train()
  File "my_encoder_decoder.py", line 298, in train
    model.build_graph()
  File "D:\vmware\share\test\chat\seq2seqmodel.py", line 197, in build_graph
    self._decoding_layer()
  File "D:\vmware\share\test\chat\seq2seqmodel.py", line 130, in _decoding_layer
    inference_decoder_output = tf.contrib.seq2seq.dynamic_decode(inference_decoder,impute_finished=False,maximum_iterations=self.max_target_sequence_length)[0]
  File "d:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "d:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "d:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "d:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2580, in _BuildLoop
    _EnforceShapeInvariant(m_var, n_var)
  File "d:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 575, in _EnforceShapeInvariant
    % (merge_var.name, m_shape, n_shape))
ValueError: The shape for decode_1/decoder/while/Merge_5:0 is not an invariant for the loop. It enters the loop with shape (1, 200), but has shape (?, 200) after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.

Does anyone know how to solve it?

**Comment by cobyC** [comment]
I encountered this problem and solved it by setting the batch_size argument for start_tokens this way.

batch_size = tf.shape(self.x)[0:1] # get batch_size from feedin self.x
start_tokens = tf.ones(batch_size, dtype=tf.int32)
emb_weights = tf.get_variable('dec_embed/lookup_table', shape=[hp.vocab_size+4, hp.hidden_units])

inference_helper = tf.contrib.seq2seq.GreedyEmbeddingHelper(
                        emb_weights,
                        start_tokens,
                        end_token=2)
inference_decoder = tf.contrib.seq2seq.BasicDecoder(
                        cell=decode_cell,
                        helper=inference_helper,
                        initial_state=tf.contrib.rnn.LSTMStateTuple(self.enc, self.enc),
                        output_layer=output_layer)
inference_outputs, _, _ = tf.contrib.seq2seq.dynamic_decode(
                        inference_decoder,
                        output_time_major=False,
                        impute_finished=True,
                        maximum_iterations=hp.max_len+2)

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
