### ISSUE TITLE
Issue while importing the library.

### ISSUE THREAD

**Issue by mjmanav4** [udacity/deep-learning#280]
import problem_unittests as tests
Traceback (most recent call last):

  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-2f2654842d05>", line 1, in <module>
    import problem_unittests as tests

  File "/home/workspace/problem_unittests.py", line 65
    assert not (int_to_vocab_word_set - vocab_to_int_word_set),\
    ^
IndentationError: unexpected indent

**Comment by abhiojha8** [comment]
@mjmanav4 Can you provide more information regarding this.

1. Which code are you trying to execute?
2. Did you use a python linter to check for indentation issues in code?

**Comment by abhiojha8** [comment]
Closing due to insufficient details and no response from the reporter.
